import requests
from datetime import datetime

# Go to https://pixe.la/ and scroll down to see the steps on how to use Pixela 

pixela_endpoint = "https://pixe.la/v1/users"
TOKEN = "" # This is generated by yourself
USERNAME = "" # Choose a username of your choice, as long as it is unique

user_params = {
    "token": TOKEN,
    "username": USERNAME,
    "agreeTermsOfService": "yes",
    "notMinor": "yes"
}

graph_endpoint = f"{pixela_endpoint}/{USERNAME}/graphs"

graph_params = {
    "id": "graph1",
    "name": "Cycling graph",
    "unit": "Km",
    "type": "float",
    "color": "shibafu"
}

headers = {
    "X-USER-TOKEN": TOKEN
}

pixel_post_endpoint = f"{graph_endpoint}/{graph_params['id']}"


today = datetime.now()

pixel_post_params = {
    "date": today.strftime("%Y%m%d"),
    "quantity": input("How many kilometers did you cycle today? ")
}

update_endpoint = f"{pixel_post_endpoint}/{today.strftime('%Y%m%d')}"

new_pixel_data = {
    "quantity": "6.5"
}

delete_endpoint = update_endpoint

response = requests.delete(url=delete_endpoint, json=pixel_post_params, headers=headers)
print(response.text)
